# Generated by Django 4.2.1 on 2023-06-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idperiodo', models.IntegerField()),
                ('año', models.CharField(max_length=45)),
                ('semestre', models.CharField(max_length=45)),
                ('Tipo', models.CharField(max_length=45)),
                ('Estado', models.CharField(max_length=45)),
                ('Fecha_inicio', models.DateField()),
                ('Fecha_cierre', models.DateField()),
            ],
        ),
    ]
